### ISSUE TITLE
Codec issues 

### ISSUE THREAD

**Issue by nihilisticzebra** [deivit24/python-steam-api#20]
Hi I keep getting this error when i run the codes
Traceback (most recent call last):
  File "z:\Project\steamapi.py", line 4, in <module>
    KEY = config("STEAM_API_KEY")
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\decouple.py", line 246, in __call__
    self._load(self.search_path or self._caller_path())
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\decouple.py", line 236, in _load
    self.config = Config(Repository(filename, encoding=self.encoding))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\decouple.py", line 151, in __init__
    for line in file_:
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by deivit24** [comment]
@nihilisticzebra hey sorry for just seeing this. hmm can I have a little bit for detail. I am assuming you created a python env and have a .env file with your `STEAM_API_KEY` ?

Also since I believe you are in Windows try this command:

`setx STEAM_API_KEY "your_api_key_here"`
