### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by 6--** [deivit24/python-steam-api#42]
Hi,

If we lookup a steam id that is banned or does not exist, we get this error

```
INFO:__main__:Fetching data for Steam ID: 8989
ERROR:__main__:Error in /steamdeeplookup: list index out of range
Traceback (most recent call last):
  File "C:\Users\AMP\Desktop\SteamBot\Steam-Discord-Bot-cleanup.py", line 45, in perform_steam_lookup
    user_data = steam.users.get_user_details(steam_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AMP\AppData\Local\Programs\Python\Python311\Lib\site-packages\steam_web_api\users.py", line 38, in get_user_details
    return {"player": user_response["players"][0]}
                      ~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

This fixed the issue for me

```
# Modify the get_user_details function in the Steam class to handle this error
def get_user_details(self, steamid):
    endpoint = "ISteamUser/GetPlayerSummaries/v0002/"
    parameters = {"key": self.api_key, "steamids": steamid}
    user_response = self._request("GET", endpoint, parameters)
    if "players" in user_response and user_response["players"]:
        return {"player": user_response["players"][0]}
    else:
        return {"player": None}
```

Thanks!

**Comment by deivit24** [comment]
hey @6--  thanks will spend the day merging stuff and taking a look at this. Will fix today and create a release later today.

**Comment by deivit24** [comment]
@6-- This should be fixed in new release! https://pypi.org/project/python-steam-api/ 2.0.3
